Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "Web server" do |web|
    web.vm.hostname = "web-AHM"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 2
    end
    web.vm.network "private_network", ip: "172.16.0.10"
    web.vm.network "public_network", ip: "10.99.0.10"
    web.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo ufw allow 'Apache Full'
      echo '<h1>Página principal de Mi Sitio Web</h1>' | sudo tee /var/www/html/index.html
      echo '<h1>Página 2</h1>' | sudo tee /var/www/html/page2.html
      echo '<h1>Página 3</h1>' | sudo tee /var/www/html/page3.html
      sudo wget -O /var/www/html/image.jpg https://via.placeholder.com/150
    SHELL
  end
end
