vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "server-AHM"
  config.vm.provider "virtualbox" do |vb|
    vb.name="UBUNTU SERVER"
    vb.memory = "2048"
    vb.cpus= 2
  end
end